Repository swgintended/Core3, pull requests merged in 2020-12, with the labels that each got.

#139 [added] GCW City Control Banners to non-stronghold cities
  MMOCoreORB/bin/scripts/screenplays/gcw/city_control_banners.lua
  MMOCoreORB/bin/scripts/screenplays/screenplays.lua
  MMOCoreORB/src/server/zone/managers/gcw/GCWManager.idl
  MMOCoreORB/src/server/zone/managers/gcw/GCWManagerImplementation.cpp
Labels: feature

#157 [Fixed] Server crash when turret kills player
  MMOCoreORB/src/server/zone/managers/player/PlayerManager.idl
  MMOCoreORB/src/server/zone/managers/player/PlayerManagerImplementation.cpp
Labels: priority: high

#144 [fixed] lair name on destroy missions
  MMOCoreORB/src/server/zone/objects/mission/DestroyMissionObjectiveImplementation.cpp
Labels: ready for qa

#160 [fixed] Buff duration for resistance enhancement
  MMOCoreORB/src/server/zone/objects/creature/commands/HealEnhanceCommand.h
Labels: ready for qa

#163 Turrets being placed in covert scanner location when a base had no defenses
  MMOCoreORB/src/server/zone/managers/gcw/GCWManagerImplementation.cpp
  MMOCoreORB/src/server/zone/objects/scene/components/DataObjectComponent.h
Labels: bug, ready for qa
